services:
  - type: web
    name: nhap-lieu-bien-che-2026
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_INITIAL_PASSWORD
        value: Admin@2026!
